### ISSUE TITLE
Doesn't work with current version of d3

### ISSUE THREAD

**Issue by v1r0x** [OpenKieler/klayjs-d3#11]
Hi,
I decided to switch from manual downloading libs to bower. I only added klayjs-d3 as dependency in my bower.json file. This downloads klayjs and d3 as dependency, but it seems that klayjs-d3 depends on an older version of d3.

``` javascript
Error: d3.rebind is not a function
b@../bower_components/klayjs-d3/dist/klayjs-d3.min.js:2:3131
a.d3kgraph@.../bower_components/klayjs-d3/dist/klayjs-d3.min.js:2:3231
$scope.initD3Graph@.../controllers/mapCtrl.js:490:29
```

Line 490 in my js file is

``` javascript
klay.d3kgraph()
```

It used to work with version 3.5.17 of d3 and the same klayjs versions and code as well.

Current versions:
klayjs: 0.4.1 build 201604131004
klayjs-d3: version 0.3.5 build 201604271204
d3: 4.2.8

**Comment by uruuru** [comment]
I fixed the d3 version to `^3.5.0`, which should resolve your issue. It looks like d3 v4.x got refactored to use ES modules.

**Comment by v1r0x** [comment]
It's working again. Thanks!
